print ('hi')
print ("hello")
print ('"1"')
print ("'2'")
print ('\'3\'')
print ('line 1 \n line 2')
print ('line 1 \t line 2')
print ('line 1 \b line 2')
print ('line 1 \\ line 2')
print ((2+3)/5*5)
print ("Added new line")
